"""secret_word

Revision ID: 288c3d692085
Revises: ad9f6e8974de
Create Date: 2025-05-06 20:24:35.336596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288c3d692085'
down_revision = 'ad9f6e8974de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret_word', sa.String(length=100), nullable=True))
        batch_op.alter_column('secret_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('current_range_low',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('current_range_high',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('guesses', schema=None) as batch_op:
        batch_op.alter_column('guess_value',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guesses', schema=None) as batch_op:
        batch_op.alter_column('guess_value',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.alter_column('current_range_high',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('current_range_low',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('secret_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('secret_word')

    op.create_table('word',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='word_pkey')
    )
    # ### end Alembic commands ###
