"""is_active_to_word

Revision ID: 7c525799e0ea
Revises: 7d6aef9fb4e2
Create Date: 2025-05-05 18:13:40.063353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c525799e0ea'
down_revision = '7d6aef9fb4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('text',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
