"""score_multiplier

Revision ID: 892b3c0b289b
Revises: 1fd052e37526
Create Date: 2025-05-06 22:59:59.365820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892b3c0b289b'
down_revision = '1fd052e37526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_multiplier', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('score_multiplier')

    # ### end Alembic commands ###
